on:
  push:
    tags:  #only trigger action when tagged with release number, i.e v0.0.1     
      - 'v*'    
  workflow_dispatch:

name: Publish Rust crate to crates.io

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Get git tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Get tag name
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Remove 'v' prefix from tag
        id: version
        run: echo "::set-output name=version::${{ steps.tag.outputs.tag#v }}"
        env:
          TAG: ${{ steps.tag.outputs.tag }}
      - name: Release details
        run: echo Release tag ${{ steps.tag.outputs.tag }}
      - run: cargo install cargo-edit
      - run: cargo set-version ${{ steps.version.outputs.version }}
        working-directory: ./ledger-models-rust
      - run: cargo publish --token ${CRATES_TOKEN}
        working-directory: ./ledger-models-rust
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
