name: Publish package to GitHub Packages
on:
  push:
    tags:  #only trigger action when tagged with release number, i.e v0.0.1     
      - 'v*'    
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ledger-models-java
jobs:
  publish-java-package:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
         java-version: '18'
         distribution: 'adopt'
    - name: Echo working directory
      run: echo pwd
    - name: Show working directory contents
      run: ls -all
    - name: Get Release Version
      run: echo "Release version is ${{ github.event.release.tag_name }}"
    - name: Release details
      run: echo ${{ github.event.release.name }} Description
    - name: Output Run Number
      run: echo ${{ github }}
    - name: Print Environment Variables
      run: env
    - name: Execute Gradle build
      run: ./gradlew publish
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run_number: ${{ github.event.release.tag_name }}
        
