name: Publish package to GitHub Packages
on:
  push:
    tags:  #only trigger action when tagged with release number, i.e v0.0.1     
      - 'v*'    
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ledger-models-java
jobs:
  publish-java-package:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
         java-version: '18'
         distribution: 'adopt'
    - name: Get git tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Echo working directory
      run: echo $pwd
    - name: Release details
      run: echo Release tag ${{ steps.tag.outputs.tag }}
    - run: TAG=${{ steps.tag.outputs.tag }}
    - run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - run: echo Version is $VERSION
    - name: Print Environment Variables
      run: env
    - name: Execute Gradle build
      run: ./gradlew publish
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run_number: ${VERSION}
        
