name: Publish package to GitHub Packages
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Output Run Number
        run: echo Run number is ${{ github.run_number }}, which will be used for artefact versions
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments:  -b ./ledger-models-java/build.gradle publish
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          run_number: ${{github.run_number}}
